
# export LANG=zh_CN.UTF-8
# export LC_ALL=zh_CN.UTF-8

# wallpaper 
# feh --bg-fill --randomize ~/archlinux.cfg/pics
# feh --bg-fill ~/archlinux.cfg/pics/afternoon.jpg
# feh --bg-fill ~/archlinux.cfg/pics/thinkdifferent.jpg
# feh --bg-fill ~/archlinux.cfg/pics/linux.png
# feh --bg-fill ~/archlinux.cfg/pics/the-evening-star.jpg
feh --bg-fill ~/archlinux.cfg/pics/dancers-in-blue.jpg
# feh --bg-fill ~/archlinux.cfg/pics/the-star.jpg

# fcitx
fcitx &

# picom
picom &

exec dwm

#startx

